#!/bin/bash
# Copyleft by dimbor <i@dimbor.ru> 2020
# based on https://habr.com/ru/post/199478/

. /etc/network/scripts/functions
dscfn="$DHCPLIB/$interface.dsc"
case $reason in
	BOUND|RENEW|REBIND|REBOOT)
		log "dhc_exit $interface $reason $new_ip_address"; fl="1"
		[ -f "$dscfn" ] && . "$dscfn"
		[ "$reason" == "BOUND" -o "$reason" == "REBOOT" ] && fl="2"
		[ -z "$saved_ip_address" -o -z "$saved_routers" -o -z "$saved_subnet" ] && {
			warn "empty saved field(s): ip=\"$saved_ip_address\" gw=\"$saved_routers\" subnet=\"$saved_subnet\""
			fl="0"
		}
		if [ "$fl" == "1" ]; then
			[ "$saved_ip_address" == "$old_ip_address" -a \
				"$saved_routers" == "$old_routers" -a \
				"$saved_network_number" == "$old_network_number" ] && fl="0"
		fi
		if [ "$fl" != "0" ]; then
			create_iface_rule_and_rtable $interface $saved_ip_address \
				$saved_routers $saved_subnet
			check_def_route || true
			# snat set here
		fi
	;;
	EXPIRE|FAIL|STOP|RELEASE)
		log "dhc_exit $interface $reason"
		flush_iface_rule_and_rtable "$interface"
		# snat clean?
		[ -f "$dscfn" ] && rm -f "$dscfn"
		check_def_route $interface || true
	;;
	PREINIT) # don't log if this stages entered
	;;
	*)
		log "dhc_exit $interface $reason!"
	;;
esac
